# Generated by Django 3.1.7 on 2021-04-11 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_username', models.TextField(blank=True, max_length=130, null=True)),
                ('first_name', models.TextField(blank=True, max_length=130, null=True)),
                ('last_name', models.TextField(blank=True, max_length=130, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.TextField(blank=True, max_length=130, null=True)),
                ('profession', models.TextField(blank=True, max_length=130, null=True)),
                ('instagramurl', models.TextField(blank=True, max_length=255, null=True)),
                ('facebookurl', models.TextField(blank=True, max_length=255, null=True)),
                ('linkdinurl', models.TextField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, max_length=255, null=True)),
                ('profile_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
